import yaml
from yaml.representer import RepresenterError

from . import KubernetesObject, RawDict


class KubernetesObjectDumper(yaml.CSafeDumper):
    def represent_undefined(self, data):
        # kubic objects, defaultdict, …
        if isinstance(data, KubernetesObject):
            return self.represent_k8s_object(data)

        if isinstance(data, RawDict):
            return self.represent_dict(data)

        elif isinstance(data, list):  # _TypedList
            return self.represent_list(data)

        raise RepresenterError("cannot represent an object", data, type(data))

    # see represent_dict()
    def represent_k8s_object(self, obj: KubernetesObject, flow_style=None):
        value = []
        node = yaml.MappingNode("tag:yaml.org,2002:map", value, flow_style=flow_style)
        if self.alias_key is not None:
            self.represented_objects[self.alias_key] = node
        best_style = True
        mapping = obj.items()
        if self.sort_keys:
            try:
                mapping = sorted(mapping)
            except TypeError:
                pass
        for item_key, item_value in mapping:
            # Skipping objets generated by __get__ accessor, but never updated.
            if isinstance(item_value, KubernetesObject) and not getattr(item_value, "__dirty"):
                continue

            # Skipping empty dict if it was generated by __get__ accessor.
            if isinstance(item_value, RawDict) and not item_value:
                continue

            node_key = self.represent_data(item_key)
            node_value = self.represent_data(item_value)
            if not (isinstance(node_key, yaml.ScalarNode) and not node_key.style):
                best_style = False
            if not (isinstance(node_value, yaml.ScalarNode) and not node_value.style):
                best_style = False
            value.append((node_key, node_value))
        if flow_style is None:
            if self.default_flow_style is not None:
                node.flow_style = self.default_flow_style
            else:
                node.flow_style = best_style
        return node


KubernetesObjectDumper.add_representer(None, KubernetesObjectDumper.represent_undefined)
