# hand crafted CDR (as sealed secret project does not provide schema)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  conversion:
    strategy: None
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                encryptedData:
                  additionalProperties:
                    format: byte
                    type: string
                  type: object
                template:
                  properties:
                    metadata:
                      $ref: "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
                    type:
                      type: string
                    data:
                      description: "Keys that should be templated using decrypted data"
                      additionalProperties:
                        type: string
                      type: object
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
